// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace server1.dbo.products
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Envelope : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Envelope"",""namespace"":""server1.dbo.products"",""fields"":[{""name"":""before"",""default"":null,""type"":[""null"",{""type"":""record"",""name"":""Value"",""namespace"":""server1.dbo.products"",""fields"":[{""name"":""id"",""type"":""int""},{""name"":""name"",""type"":""string""},{""name"":""description"",""default"":null,""type"":[""null"",""string""]},{""name"":""weight"",""default"":null,""type"":[""null"",""double""]}],""connect.name"":""server1.dbo.products.Value""}]},{""name"":""after"",""default"":null,""type"":[""null"",""Value""]},{""name"":""source"",""type"":{""type"":""record"",""name"":""Source"",""namespace"":""io.debezium.connector.sqlserver"",""fields"":[{""name"":""version"",""default"":null,""type"":[""null"",""string""]},{""name"":""connector"",""default"":null,""type"":[""null"",""string""]},{""name"":""name"",""type"":""string""},{""name"":""ts_ms"",""default"":null,""type"":[""null"",""long""]},{""name"":""change_lsn"",""default"":null,""type"":[""null"",""string""]},{""name"":""commit_lsn"",""default"":null,""type"":[""null"",""string""]},{""name"":""snapshot"",""default"":null,""type"":[""null"",""boolean""]}],""connect.name"":""io.debezium.connector.sqlserver.Source""}},{""name"":""op"",""type"":""string""},{""name"":""ts_ms"",""default"":null,""type"":[""null"",""long""]}],""connect.name"":""server1.dbo.products.Envelope""}");
		private server1.dbo.products.Value _before;
		private server1.dbo.products.Value _after;
		private io.debezium.connector.sqlserver.Source _source;
		private string _op;
		private System.Nullable<long> _ts_ms;
		public virtual Schema Schema
		{
			get
			{
				return Envelope._SCHEMA;
			}
		}
		public server1.dbo.products.Value before
		{
			get
			{
				return this._before;
			}
			set
			{
				this._before = value;
			}
		}
		public server1.dbo.products.Value after
		{
			get
			{
				return this._after;
			}
			set
			{
				this._after = value;
			}
		}
		public io.debezium.connector.sqlserver.Source source
		{
			get
			{
				return this._source;
			}
			set
			{
				this._source = value;
			}
		}
		public string op
		{
			get
			{
				return this._op;
			}
			set
			{
				this._op = value;
			}
		}
		public System.Nullable<long> ts_ms
		{
			get
			{
				return this._ts_ms;
			}
			set
			{
				this._ts_ms = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.before;
			case 1: return this.after;
			case 2: return this.source;
			case 3: return this.op;
			case 4: return this.ts_ms;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.before = (server1.dbo.products.Value)fieldValue; break;
			case 1: this.after = (server1.dbo.products.Value)fieldValue; break;
			case 2: this.source = (io.debezium.connector.sqlserver.Source)fieldValue; break;
			case 3: this.op = (System.String)fieldValue; break;
			case 4: this.ts_ms = (System.Nullable<long>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
