// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace io.debezium.connector.sqlserver
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Source : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Source"",""namespace"":""io.debezium.connector.sqlserver"",""fields"":[{""name"":""version"",""default"":null,""type"":[""null"",""string""]},{""name"":""connector"",""default"":null,""type"":[""null"",""string""]},{""name"":""name"",""type"":""string""},{""name"":""ts_ms"",""default"":null,""type"":[""null"",""long""]},{""name"":""change_lsn"",""default"":null,""type"":[""null"",""string""]},{""name"":""commit_lsn"",""default"":null,""type"":[""null"",""string""]},{""name"":""snapshot"",""default"":null,""type"":[""null"",""boolean""]}],""connect.name"":""io.debezium.connector.sqlserver.Source""}");
		private string _version;
		private string _connector;
		private string _name;
		private System.Nullable<long> _ts_ms;
		private string _change_lsn;
		private string _commit_lsn;
		private System.Nullable<bool> _snapshot;
		public virtual Schema Schema
		{
			get
			{
				return Source._SCHEMA;
			}
		}
		public string version
		{
			get
			{
				return this._version;
			}
			set
			{
				this._version = value;
			}
		}
		public string connector
		{
			get
			{
				return this._connector;
			}
			set
			{
				this._connector = value;
			}
		}
		public string name
		{
			get
			{
				return this._name;
			}
			set
			{
				this._name = value;
			}
		}
		public System.Nullable<long> ts_ms
		{
			get
			{
				return this._ts_ms;
			}
			set
			{
				this._ts_ms = value;
			}
		}
		public string change_lsn
		{
			get
			{
				return this._change_lsn;
			}
			set
			{
				this._change_lsn = value;
			}
		}
		public string commit_lsn
		{
			get
			{
				return this._commit_lsn;
			}
			set
			{
				this._commit_lsn = value;
			}
		}
		public System.Nullable<bool> snapshot
		{
			get
			{
				return this._snapshot;
			}
			set
			{
				this._snapshot = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.version;
			case 1: return this.connector;
			case 2: return this.name;
			case 3: return this.ts_ms;
			case 4: return this.change_lsn;
			case 5: return this.commit_lsn;
			case 6: return this.snapshot;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.version = (System.String)fieldValue; break;
			case 1: this.connector = (System.String)fieldValue; break;
			case 2: this.name = (System.String)fieldValue; break;
			case 3: this.ts_ms = (System.Nullable<long>)fieldValue; break;
			case 4: this.change_lsn = (System.String)fieldValue; break;
			case 5: this.commit_lsn = (System.String)fieldValue; break;
			case 6: this.snapshot = (System.Nullable<bool>)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
